packages:
    - apps/**
    - layers/**
    - workers/**
    - services/**
    - packages/**

catalog:
    jiti: ^2.5.1
    tsdown: ^0.15.2
    typescript: ^5.9.2
    vitest: ^3.2.4
    nitropack: ^2.12.9
    vue-tsc: ^3.2.1
    nuxt: ^4.2.2
    tailwindcss: ^4.5.5
