###########################
#      APP CONTAINER      #
###########################
# dockerfile-utils: ignore
FROM base AS database-manager
# dockerfile-utils: ignore
COPY --from={builder_name} /app/workers/database-manager/.output /app/.output

ENV HOST=0.0.0.0
ENV PORT=80
EXPOSE 80
ENV NODE_ENV=production

ENTRYPOINT ["node", "/app/.output/server/index.mjs" ]
